// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rescueApp.Data;

#nullable disable

namespace rescueApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("rescueApp.Models.Adopter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("adopter_apt_unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("adopter_city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("adopter_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("adopter_first_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("adopter_last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("adopter_primary_phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("adopter_primary_phone_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("adopter_secondary_phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("adopter_secondary_phone_type")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("adopter_state_province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("adopter_street_address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("adopter_zip_postal_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("date_created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("date_updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<string>("spouse_partner_roommate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("adopters", "public");
                });

            modelBuilder.Entity("rescueApp.Models.AdoptionHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("AdopterId")
                        .HasColumnType("integer");

                    b.Property<int?>("Animalid")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedByUserid")
                        .HasColumnType("uuid");

                    b.Property<int>("adopter_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("adoption_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("animal_id")
                        .HasColumnType("integer");

                    b.Property<Guid?>("created_by_user_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date_created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("return_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("Animalid");

                    b.HasIndex("CreatedByUserid");

                    b.ToTable("adoptionhistory", "public");
                });

            modelBuilder.Entity("rescueApp.Models.Animal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("adoption_status")
                        .HasColumnType("text");

                    b.Property<string>("animal_type")
                        .HasColumnType("text");

                    b.Property<string>("breed")
                        .HasColumnType("text");

                    b.Property<DateTime>("date_added")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("date_updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("story")
                        .HasColumnType("text");

                    b.Property<decimal?>("weight")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("animals", "public");
                });

            modelBuilder.Entity("rescueApp.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("date_updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("external_provider_id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("last_login_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("rescueApp.Models.AdoptionHistory", b =>
                {
                    b.HasOne("rescueApp.Models.Adopter", "Adopter")
                        .WithMany("AdoptionHistories")
                        .HasForeignKey("AdopterId");

                    b.HasOne("rescueApp.Models.Animal", "Animal")
                        .WithMany("AdoptionHistories")
                        .HasForeignKey("Animalid");

                    b.HasOne("rescueApp.Models.User", "CreatedByUser")
                        .WithMany("CreatedAdoptionHistories")
                        .HasForeignKey("CreatedByUserid");

                    b.Navigation("Adopter");

                    b.Navigation("Animal");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("rescueApp.Models.Adopter", b =>
                {
                    b.Navigation("AdoptionHistories");
                });

            modelBuilder.Entity("rescueApp.Models.Animal", b =>
                {
                    b.Navigation("AdoptionHistories");
                });

            modelBuilder.Entity("rescueApp.Models.User", b =>
                {
                    b.Navigation("CreatedAdoptionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
